repo_url: https://github.com/Interacao-Humano-Computador/2024.1-INSS/tree/main
repo_name: 2024.1-PCDF

site_name: PCDF

nav:
  - Home: index.md
  - Apresentações:
    - Apresentação 1: apresentacao/apresentacao01.md
    - Apresentação 2: apresentacao/apresentacao02.md
  - Reuniões:
      - Reunião 1: reunioes/reuniao01.md
      - Reunião 2: reunioes/reuniao02.md
      - Reunião 3: reunioes/reuniao03.md
      - Reunião 4: reunioes/reuniao04.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Cronograma Executado: planejamento/cronograma_executado.md
    - Heatmap: planejamento/heatmap.md
    - Sites Avaliados: planejamento/sitesAvaliados.md
    - Ferramentas: planejamento/ferramentas.md
    - Processos Design: planejamento/processoDesign.md
    - Site Escolhido: planejamento/siteescolhido.md
  - Análise de Requisitos I:
    - Perfil do Usuário:
        - Questionário: analise_requisitos1/perfil_do_usuario/questionario.md
        - Análise Competitiva: analise_requisitos1/perfil_do_usuario/analise_competitiva.md
        - Resultado do Perfil do Usuário: analise_requisitos1/perfil_do_usuario/resultado.md
    - Personas: analise_requisitos1/personas.md
    - Aspectos Éticos: analise_requisitos1/aspectos_éticos.md
    - Análise de tarefas:
        - Pesquisar procurados: analise_requisitos1/analise_tarefas/pesquisar_procurados.md
        - Solicitar antecedentes Criminais: analise_requisitos1/analise_tarefas/solicitar_antecedetes.md
        - Validar certidão de antecedentes criminais: analise_requisitos1/analise_tarefas/validar_antecendentes.md
        - Bloqueio de aparelho de celular roubado: analise_requisitos1/analise_tarefas/celular_roubado.md
        - Solicitar carteira de identidade: analise_requisitos1/analise_tarefas/Carteira.md
        - Registra Ocorrência: analise_requisitos1/analise_tarefas/ocorrencia.md
    - Cenários:
        - Pesquisar procurados: analise_requisitos1/cenarios/pesquisar_procurados.md
        - Solicitar antecedentes Criminais: analise_requisitos1/cenarios/solicitar_antecedetes.md
        - Validar certidão de antecedentes criminais: analise_requisitos1/cenarios/validar_antecendentes.md
        - Bloqueio de aparelho de celular roubado: analise_requisitos1/cenarios/celular_roubado.md
        - Solicitar carteira de identidade: analise_requisitos1/cenarios/Carteira.md
        - Registra Ocorrência: analise_requisitos1/cenarios/ocorrencia.md
   

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
  
  language: pt-BR
  favicon: assets/planejamento/PCDF.png
  logo:    assets/planejamento/PCDF.png
