repo_url: https://github.com/Interacao-Humano-Computador/2024.1-INSS/tree/main
repo_name: 2024.1-PCDF

site_name: PCDF

nav:
  - Home: index.md
  - Apresentações:
    - Apresentação 1: apresentacao/apresentacao01.md
    - Apresentação 2: apresentacao/apresentacao02.md
  - Reuniões:
      - Reunião 1: reunioes/reuniao01.md
      - Reunião 2: reunioes/reuniao02.md
      - Reunião 3: reunioes/reuniao03.md
      - Reunião 4: reunioes/reuniao04.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Heatmap: planejamento/heatmap.md
    - Sites Avaliados: planejamento/sitesAvaliados.md
    - Ferramentas: planejamento/ferramentas.md
    - Processos Design: planejamento/processoDesign.md
    - Site Escolhido: planejamento/siteescolhido.md
  - Análise de Requisitos I:
    - Aspectos Éticos: analise_requisitos1/aspectos_éticos.md
    - Perfil de usuário: analise_requisitos1/perfil_de_usuario.md  

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
  
  language: pt-BR
  favicon: planejamento/assets/PCDF.png
  logo: planejamento/assets/PCDF.png
