repo_url: https://interacao-humano-computador.github.io/2024.1-INSS/
repo_name: 2024.1-Grupo04

site_name: INSS

nav:
  - Home: index.md
  - Apresentações:
    - Apresentação 1: apresentacao/apresentacao01.md
  - Reuniões:
      - Reunião 1: reunioes/reuniao01.md
      - Reunião 2: reunioes/reuniao02.md
  - Planejamento:
    - Cronograma: planejamento/cronograma.md
    - Heatmap: planejamento/heatmap.md
    - Sites Avaliados: planejamento/sitesAvaliados.md
    - Ferramentas: planejamento/ferramentas.md
    - Processos Design: planejamento/processoDesign.md
    - Site Escolhido: planejamento/siteescolhido.md

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
