repo_url: https://github.com/Interacao-Humano-Computador/2024.1-INSS/tree/main
repo_name: 2024.1-PCDF

site_name: PCDF

nav:
  - Home: index.md
  - Apresentações:
    - Apresentação 1: apresentacao/apresentacao01.md
    - Apresentação 2: apresentacao/apresentacao02.md
    - Apresentação 3: apresentacao/apresentacao03.md
  - Reuniões:
      - Reunião 1: reunioes/reuniao01.md
      - Reunião 2: reunioes/reuniao02.md
      - Reunião 3: reunioes/reuniao03.md
      - Reunião 4: reunioes/reuniao04.md
      - Reunião 5: reunioes/reuniao05.md
  - Planejamento:
    - Metodologia: planejamento/metodologia.md
    - Cronograma: planejamento/cronograma.md
    - Cronograma Executado: planejamento/cronograma_executado.md
    - Heatmap: planejamento/heatmap.md
    - Sites Avaliados: planejamento/sitesAvaliados.md
    - Ferramentas: planejamento/ferramentas.md
    - Processos Design: planejamento/processoDesign.md
    - Site Escolhido: planejamento/siteescolhido.md
  - Análise de Requisitos I:
    - Aspectos Éticos: analise_requisitos1/aspectos_éticos.md
    - Perfil do Usuário:
        - Questionário: analise_requisitos1/perfil_do_usuario/questionario.md
        - Análise Competitiva: analise_requisitos1/perfil_do_usuario/analise_competitiva.md
        - Resultado do Perfil do Usuário: analise_requisitos1/perfil_do_usuario/resultado.md
    - Personas: analise_requisitos1/personas.md
    - Cenários : analise_requisitos1/cenario.md
    - Análise de tarefas:
        - HTA: analise_requisitos1/analise_tarefas/hta.md
        - GOMS: analise_requisitos1/analise_tarefas/goms.md
  - Análise de Requisitos II:
    - Princípios Gerais do Projeto: analise_requisitos2/principios_gerais.md
    - Metas de Usabilidade: analise_requisitos2/metas_usabilidade.md
    - Guia de Estilo: analise_requisitos2/guia_estilo.md
    - Características da plataforma: analise_requisitos2/caracteristicos.md

   

theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: claro
      toggle:
        icon: material/brightness-7
        name: Mudar para o modo escuro

    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Mudar para o modo claro
  
  language: pt-BR
  favicon: assets/planejamento/PCDF.png
  logo:    assets/planejamento/PCDF.png
